package output

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/compositor/kompoze/internal/converter"
	"k8s.io/apimachinery/pkg/runtime"
	sigsyaml "sigs.k8s.io/yaml"
)

const header = "# Generated by kompoze - Do not edit manually\n"

// WriteManifests serializes all K8s resources to YAML files on disk.
func WriteManifests(result *converter.ConvertResult, outputDir string, singleFile bool) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	if singleFile {
		return writeSingleFile(result, outputDir)
	}
	return writeMultipleFiles(result, outputDir)
}

// RenderManifests returns all manifests as a single YAML string (for dry-run).
func RenderManifests(result *converter.ConvertResult) (string, error) {
	var sb strings.Builder
	sb.WriteString(header)

	objects := collectObjects(result)
	for i, obj := range objects {
		if i > 0 {
			sb.WriteString("---\n")
		}
		data, err := marshalObject(obj)
		if err != nil {
			return "", err
		}
		sb.Write(data)
	}
	return sb.String(), nil
}

func writeSingleFile(result *converter.ConvertResult, outputDir string) error {
	content, err := RenderManifests(result)
	if err != nil {
		return err
	}

	path := filepath.Join(outputDir, "all-resources.yaml")
	return os.WriteFile(path, []byte(content), 0644)
}

func writeMultipleFiles(result *converter.ConvertResult, outputDir string) error {
	for _, d := range result.Deployments {
		if err := writeResource(outputDir, d.Name+"-deployment.yaml", &d); err != nil {
			return err
		}
	}
	for _, s := range result.Services {
		if err := writeResource(outputDir, s.Name+"-service.yaml", &s); err != nil {
			return err
		}
	}
	for _, cm := range result.ConfigMaps {
		if err := writeResource(outputDir, cm.Name+".yaml", &cm); err != nil {
			return err
		}
	}
	for _, pvc := range result.PVCs {
		if err := writeResource(outputDir, pvc.Name+".yaml", &pvc); err != nil {
			return err
		}
	}
	for _, ing := range result.Ingresses {
		if err := writeResource(outputDir, ing.Name+"-ingress.yaml", &ing); err != nil {
			return err
		}
	}
	for _, hpa := range result.HPAs {
		if err := writeResource(outputDir, hpa.Name+"-hpa.yaml", &hpa); err != nil {
			return err
		}
	}
	for _, pdb := range result.PDBs {
		if err := writeResource(outputDir, pdb.Name+"-pdb.yaml", &pdb); err != nil {
			return err
		}
	}
	for _, sa := range result.ServiceAccounts {
		if err := writeResource(outputDir, sa.Name+"-serviceaccount.yaml", &sa); err != nil {
			return err
		}
	}
	for _, np := range result.NetworkPolicies {
		if err := writeResource(outputDir, np.Name+"-networkpolicy.yaml", &np); err != nil {
			return err
		}
	}
	return nil
}

func writeResource(outputDir, filename string, obj runtime.Object) error {
	data, err := marshalObject(obj)
	if err != nil {
		return err
	}

	content := header + string(data)
	path := filepath.Join(outputDir, filename)
	return os.WriteFile(path, []byte(content), 0644)
}

func marshalObject(obj runtime.Object) ([]byte, error) {
	data, err := sigsyaml.Marshal(obj)
	if err != nil {
		return nil, fmt.Errorf("marshaling %T: %w", obj, err)
	}
	return data, nil
}

func collectObjects(result *converter.ConvertResult) []runtime.Object {
	var objects []runtime.Object
	for i := range result.Deployments {
		objects = append(objects, &result.Deployments[i])
	}
	for i := range result.Services {
		objects = append(objects, &result.Services[i])
	}
	for i := range result.ConfigMaps {
		objects = append(objects, &result.ConfigMaps[i])
	}
	for i := range result.PVCs {
		objects = append(objects, &result.PVCs[i])
	}
	for i := range result.Ingresses {
		objects = append(objects, &result.Ingresses[i])
	}
	for i := range result.HPAs {
		objects = append(objects, &result.HPAs[i])
	}
	for i := range result.PDBs {
		objects = append(objects, &result.PDBs[i])
	}
	for i := range result.ServiceAccounts {
		objects = append(objects, &result.ServiceAccounts[i])
	}
	for i := range result.NetworkPolicies {
		objects = append(objects, &result.NetworkPolicies[i])
	}
	return objects
}
