package output

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/compositor/kompoze/internal/converter"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func minimalResult() *converter.ConvertResult {
	replicas := int32(1)
	return &converter.ConvertResult{
		Deployments: []appsv1.Deployment{
			{
				TypeMeta:   metav1.TypeMeta{APIVersion: "apps/v1", Kind: "Deployment"},
				ObjectMeta: metav1.ObjectMeta{Name: "web"},
				Spec: appsv1.DeploymentSpec{
					Replicas: &replicas,
					Selector: &metav1.LabelSelector{
						MatchLabels: map[string]string{"app": "web"},
					},
					Template: corev1.PodTemplateSpec{
						Spec: corev1.PodSpec{
							Containers: []corev1.Container{
								{Name: "web", Image: "nginx:1.25"},
							},
						},
					},
				},
			},
		},
		Services: []corev1.Service{
			{
				TypeMeta:   metav1.TypeMeta{APIVersion: "v1", Kind: "Service"},
				ObjectMeta: metav1.ObjectMeta{Name: "web"},
				Spec: corev1.ServiceSpec{
					Ports: []corev1.ServicePort{
						{Port: 80},
					},
				},
			},
		},
	}
}

func TestWriteManifests_MultipleFiles(t *testing.T) {
	dir := t.TempDir()
	result := minimalResult()

	err := WriteManifests(result, dir, false)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Check deployment file
	data, err := os.ReadFile(filepath.Join(dir, "web-deployment.yaml"))
	if err != nil {
		t.Fatalf("reading deployment file: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "Generated by kompoze") {
		t.Error("missing header comment")
	}
	if !strings.Contains(content, "nginx:1.25") {
		t.Error("missing image in deployment")
	}

	// Check service file
	_, err = os.ReadFile(filepath.Join(dir, "web-service.yaml"))
	if err != nil {
		t.Fatalf("reading service file: %v", err)
	}
}

func TestWriteManifests_SingleFile(t *testing.T) {
	dir := t.TempDir()
	result := minimalResult()

	err := WriteManifests(result, dir, true)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "all-resources.yaml"))
	if err != nil {
		t.Fatalf("reading single file: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "---") {
		t.Error("expected YAML separator in single file")
	}
	if !strings.Contains(content, "nginx:1.25") {
		t.Error("missing image")
	}
}

func TestRenderManifests(t *testing.T) {
	result := minimalResult()

	content, err := RenderManifests(result)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.HasPrefix(content, "# Generated by kompoze") {
		t.Error("missing header")
	}
	if !strings.Contains(content, "nginx:1.25") {
		t.Error("missing image in rendered output")
	}
	if !strings.Contains(content, "---") {
		t.Error("expected YAML separator between resources")
	}
}

func TestWriteManifests_CreatesDirectory(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "dir")
	result := minimalResult()

	err := WriteManifests(result, dir, false)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if _, err := os.Stat(dir); os.IsNotExist(err) {
		t.Error("expected directory to be created")
	}
}

func TestWriteManifests_EmptyResult(t *testing.T) {
	dir := t.TempDir()
	result := &converter.ConvertResult{}

	err := WriteManifests(result, dir, false)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	entries, _ := os.ReadDir(dir)
	if len(entries) != 0 {
		t.Errorf("expected no files for empty result, got %d", len(entries))
	}
}

func TestCollectObjects(t *testing.T) {
	result := minimalResult()
	result.ConfigMaps = []corev1.ConfigMap{
		{ObjectMeta: metav1.ObjectMeta{Name: "web-config"}},
	}

	objects := collectObjects(result)
	if len(objects) != 3 {
		t.Errorf("expected 3 objects, got %d", len(objects))
	}
}
